name: 'Preternatural Upload Logs Action'
description: 'Processes and uploads logs from the default derived data path'

runs:
  using: 'composite'
  steps:
    - name: Find logs
      continue-on-error: true
      shell: bash
      run: |
        DERIVED_DATA_PATH="$HOME/Library/Developer/Xcode/DerivedData"
        echo "Searching for logs in: $DERIVED_DATA_PATH"
        
        mkdir -p ./logs
        
        # Find and copy xcresult bundles
        find "$DERIVED_DATA_PATH" -name "*.xcresult" -type d -print0 | while IFS= read -r -d '' result; do
          cp -R "$result" "./logs"
          echo "Copied $result to ./logs"
        done
        
        # Check if any logs were found and copied
        if [ -z "$(ls -A ./logs)" ]; then
          echo "No log files found in $DERIVED_DATA_PATH"
          exit 1
        fi
        
        # Create zip archive
        cd ./logs
        zip -r ../logs.zip ./*
        cd ..
        
        # Clean up Logs and ResultBundle folders in DerivedData
        echo "Cleaning up Logs and ResultBundle folders in DerivedData..."
        find "$DERIVED_DATA_PATH" -type d -name "Logs" -exec rm -rf {} +
        find "$DERIVED_DATA_PATH" -type d -name "ResultBundle" -exec rm -rf {} +
        echo "Cleanup completed"

    - name: Upload logs
      continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: logs.zip
