name: 'Preternatural Build Action'
description: 'Run Preternatural build command on repositories with a specified Xcode version'
inputs:
  xcode-version:
    description: 'Xcode version to use'
    required: false
    default: 'latest-stable'
  platforms:
    description: 'Target platforms (array of: iOS, macOS, tvOS, watchOS, visionOS, all)'
    required: false
    default: '["macOS"]'
  configurations:
    description: 'Build configurations (array of: debug, release)'
    required: false
    default: '["debug", "release"]'
  derived_data_path:
    description: 'The path to the derived data folder'
    required: false
    default: "PreternaturalBuild-DerivedData"

runs:
  using: 'composite'
  steps:
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ inputs.xcode-version }}

    - name: Install Preternatural
      if: ${{ !env.ACT }}
      shell: bash
      run: |
        brew tap PreternaturalAI/preternatural
        brew install preternatural

    - name: Restore DerivedData Cache
      uses: actions/cache/restore@v4
      with:
        path: "PreternaturalBuild-DerivedData"
        key: ${{ runner.os }}-${{ github.repository }}-${{ github.ref_name }}-derived-data

    - name: Execute preternatural build command
      id: build
      shell: bash
      run: |
        PLATFORMS=$(echo '${{ inputs.platforms }}' | tr -d '[]' | sed 's/, /,/g')
        CONFIGURATIONS=$(echo '${{ inputs.configurations }}' | tr -d '[]' | sed 's/, /,/g')
        DERIVED_DATA_PATH=${{ github.workspace }}/${{ inputs.derived_data_path }}

        function check_derived_data() {
          echo "Checking DerivedData folder at: $DERIVED_DATA_PATH"
          if [ -d "$DERIVED_DATA_PATH" ]; then
            echo "DerivedData folder exists. Contents:"
            ls -la "$DERIVED_DATA_PATH"
            echo "Total size of DerivedData:"
            du -sh "$DERIVED_DATA_PATH"
          else
            echo "DerivedData folder does not exist"
          fi
        }

        # Construct the command as a string
        PRETERNATURAL_CMD="script -q /dev/null preternatural build --derived-data-path \"$DERIVED_DATA_PATH\" --platforms $PLATFORMS --configurations $CONFIGURATIONS"
        
        echo "Constructed preternatural build command:"
        echo "${PRETERNATURAL_CMD}"
        
        check_derived_data
        
        # First attempt
        set +e  # Don't exit on error
        eval ${PRETERNATURAL_CMD} 2>&1
        BUILD_STATUS=$?
        set -e  # Return to exit on error
        
        if [ $BUILD_STATUS -ne 0 ]; then
          echo "First build attempt failed (status: $BUILD_STATUS). Cleaning derived data and retrying..."
          rm -rf "$DERIVED_DATA_PATH"
          check_derived_data
          
          # Second attempt
          eval ${PRETERNATURAL_CMD} 2>&1
          RETRY_STATUS=$?
          
          if [ $RETRY_STATUS -ne 0 ]; then
            echo "Second build attempt failed (status: $RETRY_STATUS) after cleaning derived data. Failing the workflow."
            exit 1
          fi
        fi
        
        echo "build_succeeded=true" >> $GITHUB_OUTPUT

    - name: Save DerivedData Cache
      if: steps.build.outputs.build_succeeded == 'true'
      uses: actions/cache/save@v4
      with:
        path: "PreternaturalBuild-DerivedData"
        key: ${{ runner.os }}-${{ github.repository }}-${{ github.ref_name }}-derived-data
